### PR TITLE
Workaround for Intel Port.

### PR DESCRIPTION
**Pull request by lcskrishna**
Changes Done:
1. Added the code to check the platform. 
2. Replaced the string "# pragma OPENCL EXTENSION" with its built in functions.

### CODE REVIEW

**Comment by rgiduthuri** [comment]
Thanks for your contribution.

I briefly reviewed the code and found that not all used primitives are implemented in this commit.
You can see traces of the following primitives in current source tree but missing in the commit:
  amd_lerp, amd_max3, amd_median3, amd_sad

Please consider implementing all the built-in primitives listed in:
https://www.khronos.org/registry/cl/extensions/amd/cl_amd_media_ops.txt
https://www.khronos.org/registry/cl/extensions/amd/cl_amd_media_ops2.txt

Also, use of the global variable isVendorAmd is dangerous. Please move this into 'struct AgoContext' in ago_internal.h. And few other minor changes to consider:
- pass strings as 'std::string&' in emulateBuiltinFunctions() and replaceString() instead of passing/returning std::strings by value
- call emulateBuiltinFunctions() only if isVendorAmd is false

**Comment by lcskrishna** [comment]
Hello,
Thanks for the suggestions. I have updated the code with the review comments suggested.
Chaitanya.

**Comment by rgiduthuri** [comment]
I created a new branch "amd_extensions_as_optional". Please resubmit the merge request into this new branch. The isVendorAmd variable is not initialized in all code paths, specially when context is imported. Let's make further code changes in the new branch.

Thanks

**Comment by lcskrishna** [comment]
I have resubmitted the merge request into the new branch "amd_extensions_as_optional".

Thanks

**Pull request closed without merging**
