### PR TITLE
Added install directives and debug suffix for targets in CMakeLists.txt

### PR DESCRIPTION
**Pull request by sheldonrobinson**
Added install directives to openvx/CMakeLists.txt, runcl/CMakeLists.txt, and runvx/CMakeLists.txt
Added suffix 'd' to binaries and archives of debug targets runcl, runvx, and openvx

### CODE REVIEW

**Comment by omaralvarez** [comment]
It would be awesome if this would be merged.

**Comment by rgiduthuri** [comment]
@sheldonrobinson Could you please break this merge request into separate items and re-submit them after the a sync to latest push?
I would like the cmake changes to be a separate merge request.
For now, please discard the whitespace changes as I had it in my list for a later release. 
Thanks

**Comment by rgiduthuri** [comment]
@sheldonrobinson any update?

**Comment by sheldonrobinson** [comment]
Updated the pull request, only cmake changes.
There is an issue in the update runvx/vxUtils.h that generated compile errors when I build.

I believe "#include <string>" should be "#include <cstring>"

--- a/runvx/vxUtils.h
+++ b/runvx/vxUtils.h
@@ -42,7 +42,7 @@ THE SOFTWARE.
 #include <inttypes.h>
 
 #include <sstream>
-#include <string>
+#include <cstring>
 #include <vector>
 #include <map>
 #include <list>

**Comment by rgiduthuri** [comment]
Has several CMakeLists.txt changes in the latest commits to master. Adding suffix 'd' for debug targets is seen as a problem for now.

**Pull request closed without merging**
